# -*- coding: utf-8 -*-
"""app5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n65hscEdsUJ_XL11Ht5zwvbuAmx8tBFM
"""

# ----------------------------------
# [1] 데이터 불러오기
# ----------------------------------
# 데이터 경로 유의: 루트의 data 폴더 안에 있다고 가정합니다.
df = pd.read_csv('data/sunspots_for_prophet.csv')
df['ds'] = pd.to_datetime(df['ds'])

st.subheader("📄 데이터 미리보기")
st.dataframe(df.head())

# ----------------------------------
# [2] Prophet 모델 정의 및 학습
# ----------------------------------
model = Prophet()
# 태양 흑점의 약 11년 주기를 반영합니다 (365.25일 * 11년)
model.add_seasonality(name='sunspot_cycle', period=365.25*11, fourier_order=5)
model.fit(df)

# ----------------------------------
# [3] 예측 수행
# ----------------------------------
# 30년(periods=30) 동안 연 단위(freq='Y')로 미래 날짜 생성
future = model.make_future_dataframe(periods=30, freq='Y')
forecast = model.predict(future)

# ----------------------------------
# [4] 기본 시각화
# ----------------------------------
st.subheader("📈 Prophet Forecast Plot")
fig1 = model.plot(forecast)
st.pyplot(fig1)

st.subheader("📊 Forecast Components")
fig2 = model.plot_components(forecast)
st.pyplot(fig2)

# ----------------------------------
# [5] 커스텀 시각화: 실제값 vs 예측값 + 신뢰구간
# ----------------------------------
st.subheader("📉 Custom Plot: Actual vs Predicted with Prediction Intervals")

fig3, ax = plt.subplots(figsize=(14, 6))
# 실제값
ax.plot(df["ds"], df["y"], label="Actual", color="blue", marker='o', markersize=3, linewidth=1)
# 예측값
ax.plot(forecast["ds"], forecast["yhat"], label="Predicted", color="red", linestyle="--")
# 신뢰구간
ax.fill_between(forecast["ds"], forecast["yhat_lower"], forecast["yhat_upper"], color="pink", alpha=0.4, label="Confidence Interval")

ax.set_xlabel("Year")
ax.set_ylabel("Sunspot Activity")
ax.legend(loc='upper right')
ax.grid(True)
st.pyplot(fig3)

# ----------------------------------
# [6] 잔차 분석 시각화
# ----------------------------------
st.subheader("📉 Residual Analysis (예측 오차 분석)")

# 실제값(df)과 예측값(forecast) 병합
merged = pd.merge(df, forecast[['ds', 'yhat']], on='ds', how='inner')
merged['residual'] = merged['y'] - merged['yhat']

fig4, ax2 = plt.subplots(figsize=(14, 4))
ax2.plot(merged["ds"], merged["residual"], color="purple", label="Residual")
ax2.axhline(0, color="black", linestyle="--")
ax2.set_title("Residuals (Actual - Predicted)")
ax2.legend()
ax2.grid(True)
st.pyplot(fig4)

# ----------------------------------
# [7] 잔차 통계 요약 출력
# ----------------------------------
st.subheader("📌 Residual Summary Statistics")
st.write(merged["residual"].describe())
